on:
  workflow_dispatch:
    inputs:
      dir:
        description: Namespace (Optional)
        required: false
jobs:
  Setup_repository:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - name: Networking
      run: |
        docker network create --driver bridge mesfix
    - name: Run image
      run: |
        cd ${{  github.event.inputs.dir }}/ &&

        docker build -t ${{ github.event.inputs.dir  }} . &&
        docker run --network host -it --detach --name ${{ github.event.inputs.dir  }} ${{ github.event.inputs.dir  }}
        docker exec -i  ${{ github.event.inputs.dir  }}  bash -c "pm2 start server.js"
    - name: Run main image
      run: | 
          cd api_tres
          docker build -t main .
          docker run --network host -it --detach --name main main
          docker exec -i  main bash -c "apt-get install curl && curl localhost:1000/"